### ISSUE TITLE
Unable to read files with no lexer

### ISSUE THREAD

**Issue by liiight** [Textualize/rich-cli#11]
When  trying to load a file that does not have a lexer (without specifying a lexer override via `-x`), the file fails to load:

```bash
$ rich us1.env
unable to read us1.env: no lexer for filename 'us1.env' found
```
I would like to suggest a fallback to `text` lexer, perhaps with a warning message, instead of not displaying the file

**Comment by liiight** [comment]
@willmcgugan I'd like to take a jab at doing this, if that's ok

**Comment by willmcgugan** [comment]
You're more than welcome! What does the text lexer do? Maybe you could just print it there is no lexer.

**Comment by liiight** [comment]
Text lexer just print the contents as plain text, I think that's a sensible fallback.
Maybe a switch can be added, like `--enable-lexer-fallback` ?

**Comment by giorgiberia** [comment]
I think this should be the default fallback. available even without a switch

**Comment by willmcgugan** [comment]
Try upgrading rich-cli

**Comment by giorgiberia** [comment]
I noticed this after upgrading with pipx. which is the latest version?

**Comment by giorgiberia** [comment]
this is not fixed.
