### ISSUE TITLE
Add a demo option

### ISSUE THREAD

**Issue by chemacortes** [Textualize/rich-cli#16]
Add the option `--demo` to run the demo of rich, a basic run of `python -m rich`.

When you install rich-cli with pipx, you have not direct access to the virtualenv within the rich module. Running the demo will be a quick test of the terminal.

**Comment by willmcgugan** [comment]
Will `rich --help` not suffice as a test of the terminal ?

**Comment by chemacortes** [comment]
As a text, it has not unicode chars or color palettes.

**Comment by willmcgugan** [comment]
Sorry, I don't think it is the job of rich-cli to do this. You can always run `python -m rich`.

**Comment by chemacortes** [comment]
OK. However, I have created a new package called "rich-demo". Can be invoked as `pipx run rich-demo`.
