### ISSUE TITLE
Have `rich-cli` render highlighted code to PNGs

### ISSUE THREAD

**Issue by RodrigoGiraoSerrao** [Textualize/rich-cli#18]
This is a feature request: given that `rich-cli` can highlight code in the terminal and write its output to HTML files, I thought it would be nice to have it output to an image format like PNG.

**Comment by jpaulin** [comment]
Maybe pipe the output to a proper tool? I think implementation within `rich` could easily bloat the core code into sidetracks, that take excess effort. Just an opinion. :) The idea is good! I'd like that too. Showing highlighted code would have its place, I can imagine many (even apart from t-shirt prints). And would be easier to do when the code is already a PNG image. Then syntax highlights would always work right, regardless of whether a particular text-based forum has the plugin. @RodrigoGiraoSerrao

**Comment by willmcgugan** [comment]
You can export anything in `rich-cli` to HTML, so it would be possibly to render that in a headless browser.

Going to close this issue, but its a feature that *may* appear in a future version.
