### ISSUE TITLE
Allow "no box" around code blocks for Markdown

### ISSUE THREAD

**Issue by calexicoz** [Textualize/rich-cli#27]
Hi @willmcgugan,

Thanks for making Rich!

It would be nice to allow no bounding box around code blocks for Markdown. The bounding box (lines) makes for easy reading but prevents copy/pasting of the code block content, as that also copies the lines of the box. Maybe there is already a set of options that do this, but I have not found them (yet).

Thanks :)

**Comment by willmcgugan** [comment]
I'm not keen on supplying options for MD rendering, as it could grow a huge array of them to tweak them to everyone's preferences.

However, I could be persuaded to drop the panel around code entirely. If you file an issue in [Rich](https://github.com/Textualize/rich) I'll give it some thought.

**Comment by calexicoz** [comment]
Perfectly reasonable. I'll open an issue on Rich to discuss. Closing this one. Thanks!

**Comment by calexicoz** [comment]
As a follow up, I worked around this with `sed`, and that's fine for my use case.

```bash
rich TLDR.md --force-terminal FILE | sed -e 's/[│┌┐─└┘]//g'
```
