### ISSUE TITLE
Add tail -f option

### ISSUE THREAD

**Issue by filippo82** [Textualize/rich-cli#28]
I use a software (written in Python) which logs messages to a file. I cannot change the fact that it redirects the logs to a file but I can  en`rich` the code as described [here](https://rich.readthedocs.io/en/latest/markup.html).

Question would it be feasible to add a `tail -f`-like option to `rich-cli`?

Currently this does not work: `tail -f app.log | rich - --print --force-terminal`

Thank you.

**Comment by timskovjacobsen** [comment]
I have a similar use case. I'm using [`nohup`](https://linux.die.net/man/1/nohup) to execute a long-running script, so it continues when I log out of the server.

It would be nice to use rich to color the logs as you mentioned to verify that the script runs as expected for a while before logging out: `tail -f nohup.log | rich ...`.

**Comment by michaelskyba** [comment]
https://github.com/Aider-AI/aider seems to highlight syntax lines one at a time as they're streamed from an LLM, using rich. Anyone know of any other recommended wrapper that can take stdin and write incrementally?

**Comment by harkabeeparolus** [comment]
Please note that Will created "toolong" for tailing log files.
* <https://github.com/Textualize/toolong>
