### ISSUE TITLE
Allow theme and lexer for RST and Markdown printing

### ISSUE THREAD

**Issue by wasi-master** [Textualize/rich-cli#35]
As it stands currently, rich-cli prints the rst/markdown document without considering the lexer or theme argument

Markdown: https://github.com/Textualize/rich-cli/blob/main/src/rich_cli/__main__.py#L564
RST: https://github.com/Textualize/rich-cli/blob/main/src/rich_cli/__main__.py#L570

What I suggest is to get the `--theme` argument and pass it to the `code_theme` keyword argument of the `Markdown` and `RestructuredText` class, and optionally the `--lexer` argument to the `default_lexer` parameter of the `RestructuredText` class

I may open a PR later if @willmcgugan is intrested

**Comment by willmcgugan** [comment]
Makes sense! 👍

**Comment by wasi-master** [comment]
PR coming :)
