### ISSUE TITLE
RFE: page yo' self (`rich --help --pager`)

### ISSUE THREAD

**Issue by justin-f-perez** [Textualize/rich-cli#42]
I'm getting old-man eyes and my font sizes are growing faster than my eyebrows

Could this: 
```bash
rich --help --pager
```

display the same output as `--help`, but using the `--pager`?

**Comment by willmcgugan** [comment]
Maybe. I'll look in to it next release.

PS Get yourself some reading glasses. Changed my life.

**Comment by nik-sm** [comment]
You can make this partially work using shell process substitution (https://tldp.org/LDP/abs/html/process-sub.html) - just treating the output of `rich --help` like a file:

```shell
rich --pager <(rich --help)
```

However it doesn't preserve colors. 
There might be some kind of simple shell trick (or flag for `rich`) to print color codes alongside the text (from the `rich --help`), and then the outer `rich --pager` could interpret them.
I searched a bit but couldn't find a way.
