### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by davidbrochart** [Textualize/rich-cli#48]
FYI rich-cli is now available on conda-forge, it can be installed using `conda` or `mamba`:
```bash
mamba install -c conda-forge rich-cli
```
Let me know if you want to be added as a maintainer of this package, and I'll add you.

**Comment by willmcgugan** [comment]
Fantastic, thanks. Any chance you could update the README?

Probably makes sense to add me as a maintainer.

**Comment by davidbrochart** [comment]
> Any chance you could update the README?

Done in #49.

> Probably makes sense to add me as a maintainer.

See https://github.com/conda-forge/rich-cli-feedstock/pull/1.
