### ISSUE TITLE
select/copy/find during --pager?

### ISSUE THREAD

**Issue by mlibbey** [Textualize/rich-cli#53]
I've been trying `rich --pager` as a `less` pager replacement. I've realized that I can't select words while in that mode, which prevents copy. Is there a way to allow selecting of words? (and ideally some sort of find?)

**Comment by willmcgugan** [comment]
Hold down Command or Ctrl.

Re find, we might implement that in the future.

**Comment by davidfokkema** [comment]
This does not seem to work on iTerm2 version 3.4.16 with rich-cli version 1.8.0. Holding down Cmd will highlight things that iTerm seem to think are http links, but selection is not possible. Ctrl-mouse click will immediately bring up a menu. Am I holding it wrong?

**Comment by willmcgugan** [comment]
Try option

**Comment by davidfokkema** [comment]
That works, thanks! How... could I have known this? Is this documented somewhere or would it be possible to just allow selecting text without holding the option key?

**Comment by willmcgugan** [comment]
It’s not something Textual can control. It’s a feature of you terminal.

**Comment by davidfokkema** [comment]
Ah, I see. I never encountered this before (vim, less, top work fine) but I guess it has to do with Textual being able to respond to mouse events. According to the iTerm2 docs, holding down Option disables mouse reporting and is needed for some applications. Learned something today, thanks! If I'm not the only one, maybe add a 'gotcha' to the rich-cli/textual docs? 😇

**Comment by harkabeeparolus** [comment]
> [...] I guess it has to do with Textual being able to respond to mouse events. According to the iTerm2 docs, holding down Option disables mouse reporting and is needed for some applications. 

This is correct.  Terminal applications with mouse support in terminals catch mouse events such as click and drag, that you'd normally use to select text. It's been this way for decades. This can be really annoying if you're uninterested in clicking buttons and just want to copy text, but most terminals do have some way around it. 😊
