### ISSUE TITLE
List of every supported filename extensions

### ISSUE THREAD

**Issue by gruvw** [Textualize/rich-cli#60]
Hello, could you provide a list of every filename extensions supported by rich-cli please ?

**Comment by andelink** [comment]
Rich uses pygments for its syntax highlight. You can find their lexers at [pygments.org/docs/lexers](https://pygments.org/docs/lexers).

Here are the file extensions:
https://gist.github.com/andelink/5362114ced62756a10bf27a8ac291e75

**Comment by gruvw** [comment]
great, thank you
